name: Linting

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  golangci:
    name: Linting Go code

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
